// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmmqpc_aqSXjc3IFRgoLsMR6uV2uE54JI',
    appId: '1:329756878540:web:b560a26d3b7d3a77e20469',
    messagingSenderId: '329756878540',
    projectId: 'meety-ba3ac',
    authDomain: 'meety-ba3ac.firebaseapp.com',
    storageBucket: 'meety-ba3ac.appspot.com',
    measurementId: 'G-8EH2EZ5J7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBexsfhbUuo0hUr2X8z3JM5cCNwL5r5_gw',
    appId: '1:329756878540:android:6c8f5601caf12e77e20469',
    messagingSenderId: '329756878540',
    projectId: 'meety-ba3ac',
    storageBucket: 'meety-ba3ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhXnsgsUjLq7kmu6n-ZkGZu73eJ4ThlR4',
    appId: '1:329756878540:ios:2593a8dc066fdfbee20469',
    messagingSenderId: '329756878540',
    projectId: 'meety-ba3ac',
    storageBucket: 'meety-ba3ac.appspot.com',
    iosBundleId: 'com.example.chatboolApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhXnsgsUjLq7kmu6n-ZkGZu73eJ4ThlR4',
    appId: '1:329756878540:ios:5e9a5b4d65c7a8a2e20469',
    messagingSenderId: '329756878540',
    projectId: 'meety-ba3ac',
    storageBucket: 'meety-ba3ac.appspot.com',
    iosBundleId: 'com.example.chatboolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmmqpc_aqSXjc3IFRgoLsMR6uV2uE54JI',
    appId: '1:329756878540:web:e625ba86082b9910e20469',
    messagingSenderId: '329756878540',
    projectId: 'meety-ba3ac',
    authDomain: 'meety-ba3ac.firebaseapp.com',
    storageBucket: 'meety-ba3ac.appspot.com',
    measurementId: 'G-5RVWKESRLP',
  );

}